window.MUSICK_LIVE=[
    {
        "title":  "2004 FORD F-150 - LEATHER SEATS!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  24,
        "lot":  499941,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2018 NISSAN ROGUE - AWD! 130K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  50,
        "lot":  499942,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2017 FORD FUSION - TINTED WINDOWS!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  14,
        "lot":  499943,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2018 CHRYSLER 300 - 108K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  35,
        "lot":  499944,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2017 CHEVROLET TRAVERSE - 62K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  65,
        "lot":  499945,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1998 FORD F-150 - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  21,
        "lot":  499946,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2016 CHEVROLET SONIC - TINTED WINDOWS!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  27,
        "lot":  499947,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2015 NISSAN PATHFINDER - BUYERS ASSURANCE POLICY!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  26,
        "lot":  499948,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2014 NISSAN MURANO - AWD! missing od photo!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  2,
        "lot":  499949,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2014 FORD ESCAPE - 4X4!!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  14,
        "lot":  499950,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2014 RAM CARGO VAN - SPACIOUS CARGO!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  13,
        "lot":  499951,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2013 KIA SOUL - GREAT COMMUTRE!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  36,
        "lot":  499952,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2013 CHEVROLET MALIBU -",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  21,
        "lot":  499953,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2012 DODGE CHARGER - 105K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  56,
        "lot":  499954,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2012 FORD FIESTA - BUYER\u0027S ASSURANCE POLICY!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  22,
        "lot":  499955,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2012 NISSAN SENTRA - SUNROOF!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  12,
        "lot":  499956,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2011 SUBARU OUTBACK - BUYER\u0027S ASSURANCE POLICY!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  11,
        "lot":  499957,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2011 FORD FUSION - TINTED WINDOWS!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  11,
        "lot":  499958,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2011 SUBARU LEGACY - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  23,
        "lot":  499959,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2010 LEXUS RX 350 - SUNROOF!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  34,
        "lot":  499960,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2009 FORD EXCAPE - HYBRID!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  9,
        "lot":  499961,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2008 BMW 5 SERIES -",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  9,
        "lot":  499962,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2009 AUDI Q5 -",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  30,
        "lot":  499963,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2006 LAND RANGE ROVER - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  19,
        "lot":  499964,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2005 HONDA ACCORD - BUYER\u0027S ASSURANCE POLICY",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  31,
        "lot":  499965,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2000 HONDA ODYSSEY - 3RD ROW SEATING!",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  12,
        "lot":  501444,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Springfield Armory XD(M)-40 3.8\" .40 S\u0026W Semi-Automatic Pistol, 16+1 Capacity",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  33,
        "lot":  499966,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Mossberg 500 20 Gauge Pump-Action Shotgun, 26\" Barrel, Accu-Choke, Serial T715543",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  28,
        "lot":  499967,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Smith \u0026 Wesson SW9VE 9mm Pistol, Stainless Slide, 4\" Barrel, 16+1 Capacity, Polymer Frame, SN: DYJ5211",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  21,
        "lot":  499968,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Anderson AM-15 AR-15 Pistol, 5.56 NATO, 16\" DTI Barrel, 1:9 Twist, SB Tactical Brace, SN: 22074166",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  28,
        "lot":  499969,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Raven Arms MP-25 Chrome .25 ACP Semiautomatic Pistol, 2.5\" Barrel, Wood Grips, SN 1037157",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  8,
        "lot":  499970,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Mercury Dimes Lot: 1942 \u0026 1945-S, 90% Silver, Circulated, U.S. Mint",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  3,
        "lot":  499971,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Swiss M1957 Bayonet for STGW 57, Wenger, 9.5\" Steel Blade, Scabbard \u0026 Frog Included",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  9,
        "lot":  499972,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(3) 60 Rounds 5.56mm M193 Ball Ammo, Lake City (SMQ), 10rd Stripper Clips, 55gr FMJ, 2019 Lot",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  5,
        "lot":  499973,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1950-S Washington Quarter MS68+ Silver 25¢ San Francisco Mint, Rare High Grade, Flanagan Design",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  50,
        "lot":  499974,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1943 \u0026 1944 S Mercury Dimes, 90% Silver, San Francisco Mint, in 2x2 Holders",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  6,
        "lot":  499975,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Gerber StrongArm Fixed Blade Knife Coyote Brown 4.8\" 420HC Blade, Sheath, Drop Point, USA Made",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  33,
        "lot":  499976,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Pokémon GO V Battle Deck Bundle: Mewtwo vs. Melmetal, 2 Decks, 3 Booster Packs, Promo Cards",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  31,
        "lot":  499977,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(3) .223 Remington 55gr FMJ Igman Ammunition, 60 Rounds, Brass Case, Boxer-Primed, 3 Boxes",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  11,
        "lot":  499978,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "AKM Type I Bayonet, 5.75\" Blade, Brown Bakelite Handle, Matching Serial SAE4441, w/Scabbard",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  14,
        "lot":  499979,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1881-O Morgan Silver Dollar, New Orleans Mint, 90% Silver, $1 Coin",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  24,
        "lot":  499980,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(5) Gold-Plated Donald J. Trump $1000 Novelty Bills, Faux U.S. Currency, GOLD99999999 Serial",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  1,
        "lot":  499981,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(3) 60 Rounds 5.56x45mm M193 Ball Ammo on Stripper Clips, SMQ Lot, Brass Case, USGI",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  5,
        "lot":  499982,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1959, 1962, 1966 Mexico 1 Peso Coins – Bust of Morelos – Mo Mint – 10% Silver, 34.5mm",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  5,
        "lot":  499983,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(4) Idaho Goldbacks 1/4 Denomination 2026, 1/4000th Troy Oz 24K Gold Note, Serial AH88041",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  7,
        "lot":  499984,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Pokémon TCG Mega Evolution: Perfect Order Elite Trainer Box with Tyrunt Promo Card",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  11,
        "lot":  499985,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "Mosin-Nagant M1891/30 Cruciform Spike Bayonet, 16.75\" Blade, Press Stud Locking, Soviet Issue",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  16,
        "lot":  499986,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(1) Amazon Fire HD 10, W/O Charger",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  16,
        "lot":  499987,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "(3) .223 Remington 55gr FMJ Brass Ammo 3 Boxes/60 Rounds Igman IK21 Factory Sealed",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  11,
        "lot":  499988,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "1944-S \u0026 1945-S Mercury Dimes, 90% Silver, Circulated, San Francisco Mint, Set of 2",
        "category":  null,
        "condition":  null,
        "currentBid":  0,
        "askingBid":  0,
        "bidCount":  3,
        "lot":  499989,
        "auctionId":  898,
        "endsAt":  null
    },
    {
        "title":  "2006 FORD F-250 - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  4200,
        "askingBid":  4300,
        "bidCount":  15,
        "lot":  500692,
        "auctionId":  899,
        "endsAt":  1787094312
    },
    {
        "title":  "2019 FORD ESCAPE - 4x4! - 63K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  9100,
        "askingBid":  9200,
        "bidCount":  22,
        "lot":  500693,
        "auctionId":  899,
        "endsAt":  1787094252
    },
    {
        "title":  "2017 HYUNDAI SANTA FE - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  4000,
        "askingBid":  4100,
        "bidCount":  22,
        "lot":  500694,
        "auctionId":  899,
        "endsAt":  1787094252
    },
    {
        "title":  "2016 NISSAN MAXIMA - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  3800,
        "askingBid":  3900,
        "bidCount":  25,
        "lot":  500695,
        "auctionId":  899,
        "endsAt":  1787094252
    },
    {
        "title":  "2014 INFINITI QX60 - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  1900,
        "askingBid":  1950,
        "bidCount":  13,
        "lot":  500696,
        "auctionId":  899,
        "endsAt":  1787094192
    },
    {
        "title":  "2014 CHEVROLET SPARK - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  1300,
        "askingBid":  1350,
        "bidCount":  18,
        "lot":  500697,
        "auctionId":  899,
        "endsAt":  1787094192
    },
    {
        "title":  "2009 MINI COOPER - 88K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  1450,
        "askingBid":  1500,
        "bidCount":  20,
        "lot":  500698,
        "auctionId":  899,
        "endsAt":  1787094192
    },
    {
        "title":  "2016 KIA SOUL - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1200,
        "askingBid":  1250,
        "bidCount":  4,
        "lot":  500699,
        "auctionId":  899,
        "endsAt":  1787094132
    },
    {
        "title":  "2015 CADILLAC ATS -BLUETOOTH!",
        "category":  null,
        "condition":  null,
        "currentBid":  3800,
        "askingBid":  3900,
        "bidCount":  14,
        "lot":  500700,
        "auctionId":  899,
        "endsAt":  1787094132
    },
    {
        "title":  "2014 DODGE JOURNEY SXT - BLUETOOTH!",
        "category":  null,
        "condition":  null,
        "currentBid":  1850,
        "askingBid":  1900,
        "bidCount":  6,
        "lot":  500701,
        "auctionId":  899,
        "endsAt":  1787094132
    },
    {
        "title":  "2013 AUDI A8 - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  1550,
        "askingBid":  1600,
        "bidCount":  22,
        "lot":  500702,
        "auctionId":  899,
        "endsAt":  1787094072
    },
    {
        "title":  "2009 KIA SORENTO - BLUETOOTH!",
        "category":  null,
        "condition":  null,
        "currentBid":  1900,
        "askingBid":  1950,
        "bidCount":  14,
        "lot":  500703,
        "auctionId":  899,
        "endsAt":  1787094072
    },
    {
        "title":  "2009 DODGE JOURNEY - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  2200,
        "askingBid":  2250,
        "bidCount":  8,
        "lot":  500704,
        "auctionId":  899,
        "endsAt":  1787094072
    },
    {
        "title":  "2009 KIA RIO - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  750,
        "askingBid":  800,
        "bidCount":  3,
        "lot":  500705,
        "auctionId":  899,
        "endsAt":  1787094012
    },
    {
        "title":  "2008 SUBARU OUTBACK - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1200,
        "askingBid":  1250,
        "bidCount":  7,
        "lot":  500706,
        "auctionId":  899,
        "endsAt":  1787094012
    },
    {
        "title":  "2007 HYUNDAI SONATA - SUNROOF!",
        "category":  null,
        "condition":  null,
        "currentBid":  550,
        "askingBid":  600,
        "bidCount":  2,
        "lot":  500707,
        "auctionId":  899,
        "endsAt":  1787094012
    },
    {
        "title":  "2004 BMW X3 - LEATHER SEATS!",
        "category":  null,
        "condition":  null,
        "currentBid":  1300,
        "askingBid":  1350,
        "bidCount":  18,
        "lot":  500708,
        "auctionId":  899,
        "endsAt":  1787093952
    },
    {
        "title":  "2006 KIA SORENTO - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  900,
        "askingBid":  950,
        "bidCount":  10,
        "lot":  500709,
        "auctionId":  899,
        "endsAt":  1787093952
    },
    {
        "title":  "2006 KIA OPTIMA - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  650,
        "askingBid":  700,
        "bidCount":  5,
        "lot":  500710,
        "auctionId":  899,
        "endsAt":  1787093952
    },
    {
        "title":  "2000 GMC SIERRA 1500 - 4x4!",
        "category":  null,
        "condition":  null,
        "currentBid":  1500,
        "askingBid":  1550,
        "bidCount":  15,
        "lot":  500711,
        "auctionId":  899,
        "endsAt":  1787093892
    },
    {
        "title":  "2000 GMC YUKON - 4x4!",
        "category":  null,
        "condition":  null,
        "currentBid":  600,
        "askingBid":  650,
        "bidCount":  3,
        "lot":  500712,
        "auctionId":  899,
        "endsAt":  1787093892
    },
    {
        "title":  "BANK REPO - LOTS 322 - 326",
        "category":  null,
        "condition":  null,
        "currentBid":  500000,
        "askingBid":  500000,
        "bidCount":  0,
        "lot":  500713,
        "auctionId":  899,
        "endsAt":  1787093892
    },
    {
        "title":  "BANK REPO - 2013 FORD F-150 - RWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1150,
        "askingBid":  1200,
        "bidCount":  8,
        "lot":  500714,
        "auctionId":  899,
        "endsAt":  1787093832
    },
    {
        "title":  "BANK REPO - 2008 GMC CANYON - 4x4!",
        "category":  null,
        "condition":  null,
        "currentBid":  3100,
        "askingBid":  3200,
        "bidCount":  45,
        "lot":  501447,
        "auctionId":  899,
        "endsAt":  1787093832
    },
    {
        "title":  "BANK REPO - 2015 DODGE DART - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1850,
        "askingBid":  1900,
        "bidCount":  15,
        "lot":  500715,
        "auctionId":  899,
        "endsAt":  1787093832
    },
    {
        "title":  "BANK REPO - 2013 CADILLAC ATS - BACKUP CAMERA!",
        "category":  null,
        "condition":  null,
        "currentBid":  1050,
        "askingBid":  1100,
        "bidCount":  12,
        "lot":  500716,
        "auctionId":  899,
        "endsAt":  1787093772
    },
    {
        "title":  "BANK REPO - 2012 VOLKSWAGEN GTI",
        "category":  null,
        "condition":  null,
        "currentBid":  700,
        "askingBid":  750,
        "bidCount":  5,
        "lot":  500717,
        "auctionId":  899,
        "endsAt":  1787093772
    },
    {
        "title":  "BANK REPO - 2005 MINI COOPER",
        "category":  null,
        "condition":  null,
        "currentBid":  600,
        "askingBid":  650,
        "bidCount":  3,
        "lot":  500718,
        "auctionId":  899,
        "endsAt":  1787093772
    },
    {
        "title":  "Iver Johnson Champion .410 Gauge Single-Shot Shotgun, 26\" Barrel, Serial #96282",
        "category":  null,
        "condition":  null,
        "currentBid":  80,
        "askingBid":  85,
        "bidCount":  7,
        "lot":  500719,
        "auctionId":  899,
        "endsAt":  1787093712
    },
    {
        "title":  "Taurus Ultra-Lite .38 Special +P Revolver, 2\" Barrel, 5-Round Capacity",
        "category":  null,
        "condition":  null,
        "currentBid":  260,
        "askingBid":  270,
        "bidCount":  8,
        "lot":  500720,
        "auctionId":  899,
        "endsAt":  1787093712
    },
    {
        "title":  "Glock 23 Gen 4 .40 S\u0026W, Custom Stippled Grip, Fiber Optic Sights, Serial UXS788",
        "category":  null,
        "condition":  null,
        "currentBid":  215,
        "askingBid":  220,
        "bidCount":  27,
        "lot":  500721,
        "auctionId":  899,
        "endsAt":  1787093712
    },
    {
        "title":  "Glenfield Model 25 Bolt Action .22 S/L/LR Rifle, 22\" Barrel, Detachable Mag, Wood Stock, Serial 26581417",
        "category":  null,
        "condition":  null,
        "currentBid":  110,
        "askingBid":  115,
        "bidCount":  13,
        "lot":  500722,
        "auctionId":  899,
        "endsAt":  1787093652
    },
    {
        "title":  "Smith \u0026 Wesson M\u0026P 9 Shield 9mm, Polymer Frame, 3.1\" Barrel, Serial HKJ5369, USA Made",
        "category":  null,
        "condition":  null,
        "currentBid":  145,
        "askingBid":  150,
        "bidCount":  20,
        "lot":  500723,
        "auctionId":  899,
        "endsAt":  1787093652
    },
    {
        "title":  "Jacobsen HR 9016 Turbo 4WD Wide-Area Mower, 16 ft Deck, 65 hp Diesel Engine, 9 Rotary Blades *Non Running*",
        "category":  null,
        "condition":  null,
        "currentBid":  800,
        "askingBid":  850,
        "bidCount":  15,
        "lot":  500724,
        "auctionId":  899,
        "endsAt":  1787093652
    },
    {
        "title":  "1893-O Barber Quarter 25¢ Silver Coin, G4 Grade, New Orleans Mint, 90% Silver",
        "category":  null,
        "condition":  null,
        "currentBid":  17,
        "askingBid":  18,
        "bidCount":  12,
        "lot":  500725,
        "auctionId":  899,
        "endsAt":  1787093592
    },
    {
        "title":  "CHARD DES-2DSS Electric Smoker, 650W, Digital Controls, Viewing Window (Functional)",
        "category":  null,
        "condition":  null,
        "currentBid":  47,
        "askingBid":  49,
        "bidCount":  11,
        "lot":  500726,
        "auctionId":  899,
        "endsAt":  1787093592
    },
    {
        "title":  "Platinum Ruby \u0026 Diamond Ring, 1.06 ct Oval Ruby, 0.36 ct Diamonds, Certificate K42E11-EA14142, Appraised",
        "category":  null,
        "condition":  null,
        "currentBid":  155,
        "askingBid":  160,
        "bidCount":  29,
        "lot":  500727,
        "auctionId":  899,
        "endsAt":  1787093592
    },
    {
        "title":  "1942-D Walking Liberty Half Dollar, Silver, 50¢ Coin, Denver Mint, Circulated",
        "category":  null,
        "condition":  null,
        "currentBid":  25,
        "askingBid":  27,
        "bidCount":  7,
        "lot":  500728,
        "auctionId":  899,
        "endsAt":  1787093532
    },
    {
        "title":  "14K Yellow Gold Ring 1.47CTW, 1.06Ct Center Diamond, H/I1, GGA Appraisal #GGA063848 RN033559 (Please Inspect In Person) Size 10",
        "category":  null,
        "condition":  null,
        "currentBid":  340,
        "askingBid":  350,
        "bidCount":  38,
        "lot":  500729,
        "auctionId":  899,
        "endsAt":  1787093532
    },
    {
        "title":  "Antique \"BABY\" Cast Iron Toy Stove with Accessories, Circa 1880-1920, 13\" x 13\" x 15.5\"",
        "category":  null,
        "condition":  null,
        "currentBid":  35,
        "askingBid":  37,
        "bidCount":  30,
        "lot":  500730,
        "auctionId":  899,
        "endsAt":  1787093532
    },
    {
        "title":  "18K White Gold Marquise Tanzanite (3.75Ct) \u0026 Diamond (0.87Ct) Ring GGA061479, RN033039 (Please Inspect In Person) Size 6.5",
        "category":  null,
        "condition":  null,
        "currentBid":  460,
        "askingBid":  470,
        "bidCount":  38,
        "lot":  500731,
        "auctionId":  899,
        "endsAt":  1787093472
    },
    {
        "title":  "1954-D Franklin Silver Half Dollar, 90% Silver, Denver Mint, Benjamin Franklin Liberty Bell Design",
        "category":  null,
        "condition":  null,
        "currentBid":  24,
        "askingBid":  25,
        "bidCount":  6,
        "lot":  500732,
        "auctionId":  899,
        "endsAt":  1787093472
    },
    {
        "title":  "Antique Toledo Cooker Co. Conservo Steam Cooker/Oven with Copper Bottom, Circa 1907",
        "category":  null,
        "condition":  null,
        "currentBid":  11,
        "askingBid":  12,
        "bidCount":  7,
        "lot":  500733,
        "auctionId":  899,
        "endsAt":  1787093472
    },
    {
        "title":  "14K White Gold Lady\u0027s Ring, 0.84Ct Tsavorite, 0.49Ct Diamonds, RN035436, Appraised $3,870 (Please Inspect In Person) Size 6.5",
        "category":  null,
        "condition":  null,
        "currentBid":  145,
        "askingBid":  150,
        "bidCount":  13,
        "lot":  500734,
        "auctionId":  899,
        "endsAt":  1787093412
    },
    {
        "title":  "1963 Franklin Half Dollar, 90% Silver, Circulated Condition",
        "category":  null,
        "condition":  null,
        "currentBid":  23,
        "askingBid":  24,
        "bidCount":  3,
        "lot":  500735,
        "auctionId":  899,
        "endsAt":  1787093412
    },
    {
        "title":  "Custom Damascus Cleaver, Hammered Hex Blade, Colored Stabilized Wood Handle, Full Tang",
        "category":  null,
        "condition":  null,
        "currentBid":  12,
        "askingBid":  13,
        "bidCount":  8,
        "lot":  500736,
        "auctionId":  899,
        "endsAt":  1787093412
    },
    {
        "title":  "1958-D Franklin Half Dollar, 90% Silver, Circulated Condition",
        "category":  null,
        "condition":  null,
        "currentBid":  24,
        "askingBid":  25,
        "bidCount":  4,
        "lot":  500737,
        "auctionId":  899,
        "endsAt":  1787093352
    },
    {
        "title":  "100 Rounds 9MM Luger Handloaded Ammo, 115Gr Hornady XTP, Brass Case, Bullseye Powder",
        "category":  null,
        "condition":  null,
        "currentBid":  17,
        "askingBid":  18,
        "bidCount":  9,
        "lot":  500738,
        "auctionId":  899,
        "endsAt":  1787093352
    },
    {
        "title":  "Custom Handmade Damascus Steel Cleaver-Style Fixed-Blade Knife With Wood Resin Handle And Leather Sheath",
        "category":  null,
        "condition":  null,
        "currentBid":  9,
        "askingBid":  10,
        "bidCount":  5,
        "lot":  500739,
        "auctionId":  899,
        "endsAt":  1787093352
    },
    {
        "title":  "Singer Model 20 Hand-Crank Toy Sewing Machine, Circa 1926–1930, Black with Gold Decals (7\"x4\"x 6.5\")",
        "category":  null,
        "condition":  null,
        "currentBid":  50,
        "askingBid":  55,
        "bidCount":  12,
        "lot":  500740,
        "auctionId":  899,
        "endsAt":  1787093292
    },
    {
        "title":  "2021 TESLA MODEL Y - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  5600,
        "askingBid":  5700,
        "bidCount":  38,
        "lot":  499938,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "1996 TOYOTA TACOMA - WOODEN STAKE BED!",
        "category":  null,
        "condition":  null,
        "currentBid":  5500,
        "askingBid":  5600,
        "bidCount":  38,
        "lot":  499940,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2019 TOYOTA PRIUS - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1100,
        "askingBid":  1150,
        "bidCount":  13,
        "lot":  499530,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2018 TESLA MODEL 3 - 15IN TOUCH SCREEN! CHARGES FULLY!",
        "category":  null,
        "condition":  null,
        "currentBid":  7200,
        "askingBid":  7300,
        "bidCount":  44,
        "lot":  499531,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2017 JEEP WRANGLER - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  5100,
        "askingBid":  5200,
        "bidCount":  43,
        "lot":  498632,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2014 PORSCHE CAYENNE - DIESEL!",
        "category":  null,
        "condition":  null,
        "currentBid":  3700,
        "askingBid":  3800,
        "bidCount":  19,
        "lot":  498633,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2015 JEEP CHEROKEE - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  1100,
        "askingBid":  1150,
        "bidCount":  13,
        "lot":  498634,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2015 FORD MUSTANG - CONVERTIBLE !",
        "category":  null,
        "condition":  null,
        "currentBid":  3500,
        "askingBid":  3600,
        "bidCount":  43,
        "lot":  498635,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2013 DODGE CHARGER - TOUCH SCREEN STEREO!",
        "category":  null,
        "condition":  null,
        "currentBid":  1650,
        "askingBid":  1700,
        "bidCount":  19,
        "lot":  498636,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2013 INFINITI JX35 - ECO \u0026 SPORT MODE!",
        "category":  null,
        "condition":  null,
        "currentBid":  1750,
        "askingBid":  1800,
        "bidCount":  26,
        "lot":  498637,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2010 LEXUS RX350 - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1750,
        "askingBid":  1800,
        "bidCount":  24,
        "lot":  498638,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2008 BMW X5 - 114K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  1250,
        "askingBid":  1300,
        "bidCount":  14,
        "lot":  498639,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2007 CHEVROLET HHR - SUNROOF!",
        "category":  null,
        "condition":  null,
        "currentBid":  900,
        "askingBid":  950,
        "bidCount":  9,
        "lot":  498640,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2007 CHEVROLET TAHOE - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  550,
        "askingBid":  600,
        "bidCount":  2,
        "lot":  498641,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2005 CADILLAC DEVILLE - LEATHER SEATS!",
        "category":  null,
        "condition":  null,
        "currentBid":  800,
        "askingBid":  850,
        "bidCount":  5,
        "lot":  498642,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2000 BMW 740i SPORT- 135K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  1350,
        "askingBid":  1400,
        "bidCount":  16,
        "lot":  501445,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "1976 CHEVROLET C2500 - SQUARE BODY! UNKNOWN MODS!",
        "category":  null,
        "condition":  null,
        "currentBid":  700,
        "askingBid":  750,
        "bidCount":  4,
        "lot":  499522,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2023 TRAVEL LITE ROVE LIGHT 14FD",
        "category":  null,
        "condition":  null,
        "currentBid":  6400,
        "askingBid":  6500,
        "bidCount":  25,
        "lot":  499523,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "GOLD SHAKE PLATE!!",
        "category":  null,
        "condition":  null,
        "currentBid":  250,
        "askingBid":  250,
        "bidCount":  0,
        "lot":  500691,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Smith \u0026 Wesson Model 29-10 .44 Magnum Engraved 4\" Revolver, Walnut Grips, Blue Finish, Case",
        "category":  null,
        "condition":  null,
        "currentBid":  460,
        "askingBid":  470,
        "bidCount":  24,
        "lot":  498643,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "New England Firearms Pardner SB1 20 Gauge Single-Shot 3\" Full Choke Shotgun NB294432",
        "category":  null,
        "condition":  null,
        "currentBid":  50,
        "askingBid":  55,
        "bidCount":  1,
        "lot":  499524,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Anderson AM-15 AR Pistol, Multi-Cal, 5.5\" Barrel, \"We The People\" Engraving, S/N 22056069",
        "category":  null,
        "condition":  null,
        "currentBid":  420,
        "askingBid":  430,
        "bidCount":  22,
        "lot":  498644,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Springfield Model 15-B .22 S/L/LR Bolt Action Single Shot Rifle, 24\" Barrel, Wood Stock (Incomplete)",
        "category":  null,
        "condition":  null,
        "currentBid":  50,
        "askingBid":  50,
        "bidCount":  0,
        "lot":  499525,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Taurus PT 24/7 .45 ACP Semi-Auto Pistol, 4.2” Barrel, 12+1 Mag, Serial NYF02758",
        "category":  null,
        "condition":  null,
        "currentBid":  110,
        "askingBid":  115,
        "bidCount":  10,
        "lot":  498645,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Springfield Model 62-B Bolt-Action Rifle, .22 S/L/LR, 24\" Barrel, Vintage Stevens Arms (Incomplete)",
        "category":  null,
        "condition":  null,
        "currentBid":  50,
        "askingBid":  50,
        "bidCount":  0,
        "lot":  499526,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "LRB Arms M15SA AR-15 Rifle, 5.56/.223 Wylde, HERA 12\" Rail, Stainless 1:9 Barrel, SN#040461",
        "category":  null,
        "condition":  null,
        "currentBid":  280,
        "askingBid":  290,
        "bidCount":  19,
        "lot":  498646,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Camouflage Synthetic Break-Barrel Air Rifle with Scope, Approx. 44\" Length",
        "category":  null,
        "condition":  null,
        "currentBid":  50,
        "askingBid":  50,
        "bidCount":  0,
        "lot":  499527,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Taurus G2S 9mm, FDE Frame, 3.25\" Barrel, 7+1 Capacity, Serial TMW34268, 1 Magazine",
        "category":  null,
        "condition":  null,
        "currentBid":  225,
        "askingBid":  230,
        "bidCount":  19,
        "lot":  498647,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "28.86ct Diamond Tennis Necklace, 14K White Gold, 17.5in, AIGL Appraisal K53D511-EA22992",
        "category":  null,
        "condition":  null,
        "currentBid":  3400,
        "askingBid":  3500,
        "bidCount":  76,
        "lot":  498648,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum Multi-Color 46.72ct Sapphire \u0026 Diamond Tennis Bracelet, Walker Gruen, GIA Certified, Appraisal $86,940.00",
        "category":  null,
        "condition":  null,
        "currentBid":  500,
        "askingBid":  550,
        "bidCount":  35,
        "lot":  498649,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum 900 Ruby Ring 8.19ct GIA Certified, 0.74ct Diamond, Aaron Gofflieb, Appraisal $32,268",
        "category":  null,
        "condition":  null,
        "currentBid":  260,
        "askingBid":  270,
        "bidCount":  28,
        "lot":  498650,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "18K White Gold Paraiba \u0026 Rubellite Tourmaline Diamond Drop Earrings, 26.00 ctw, Appraised $32,570, GGA/GIA Cert",
        "category":  null,
        "condition":  null,
        "currentBid":  260,
        "askingBid":  270,
        "bidCount":  43,
        "lot":  498651,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "14K White Gold 7.88ct Tanzanite \u0026 Diamond Ring, GIA Appraisal, Orianne, GAL Certified",
        "category":  null,
        "condition":  null,
        "currentBid":  340,
        "askingBid":  350,
        "bidCount":  36,
        "lot":  498652,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum 950 Fancy Black Diamond 7.50ct Pendant Necklace w/1.51ct Colorless Accents \u0026 Appraisal",
        "category":  null,
        "condition":  null,
        "currentBid":  360,
        "askingBid":  370,
        "bidCount":  50,
        "lot":  498653,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum Heart Sapphire \u0026 Diamond Ring 3.98ct GIA Certified PT900 0.77ct VS1/SI1",
        "category":  null,
        "condition":  null,
        "currentBid":  280,
        "askingBid":  290,
        "bidCount":  21,
        "lot":  498654,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum Ring 2.72ct GIA No-Heat Purple Spinel, 0.87ct F-G VS1-SI1 Diamonds",
        "category":  null,
        "condition":  null,
        "currentBid":  360,
        "askingBid":  370,
        "bidCount":  19,
        "lot":  498655,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "14K White Gold Tanzanite (7.31ct) \u0026 Diamond (0.92ct, 40pcs) Pendant Necklace, GGA Appraised",
        "category":  null,
        "condition":  null,
        "currentBid":  290,
        "askingBid":  300,
        "bidCount":  20,
        "lot":  498656,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "14K Two Tone Gold Necklace, 16.27ct Pear Opal, 1.93ct Diamond Pendant, Appraised $22,970, Italy",
        "category":  null,
        "condition":  null,
        "currentBid":  260,
        "askingBid":  270,
        "bidCount":  40,
        "lot":  498657,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum Ring with 3.60 ct Emerald and 0.60 ct Diamonds",
        "category":  null,
        "condition":  null,
        "currentBid":  205,
        "askingBid":  210,
        "bidCount":  12,
        "lot":  498658,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum Ring, 2.79ct Natural Blue Sapphire, 0.65ct VS1 Diamonds, GIA Certified, PT900",
        "category":  null,
        "condition":  null,
        "currentBid":  240,
        "askingBid":  245,
        "bidCount":  24,
        "lot":  498659,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "18K White Gold 2.44ct Blue Sapphire GIA Certified Ring w/ 0.80ctw Diamond Accents, Appraised",
        "category":  null,
        "condition":  null,
        "currentBid":  800,
        "askingBid":  850,
        "bidCount":  20,
        "lot":  498660,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum \u0026 18K Gold Ring, 3.34ct Emerald, 0.73ct VS1-VS2 Diamond, GIA/AIGL Cert",
        "category":  null,
        "condition":  null,
        "currentBid":  290,
        "askingBid":  300,
        "bidCount":  42,
        "lot":  498661,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman 18K White Gold Ring, 2.96ct Emerald, 1.05ct G/SI Diamond, AIGL Certified",
        "category":  null,
        "condition":  null,
        "currentBid":  310,
        "askingBid":  320,
        "bidCount":  45,
        "lot":  498662,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum \u0026 18K Ring, 3.44ct Russian Emerald, 0.50ct Diamonds, GIA \u0026 AIGL Certified",
        "category":  null,
        "condition":  null,
        "currentBid":  280,
        "askingBid":  290,
        "bidCount":  15,
        "lot":  498663,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum 900 Ring with 5.12ct GIA Ruby, 0.41ct Diamond Halo, AIGL Appraised",
        "category":  null,
        "condition":  null,
        "currentBid":  200,
        "askingBid":  205,
        "bidCount":  28,
        "lot":  498664,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman PT900 Platinum Ring 2.65ct Brownish Pink Orange Sapphire, 0.70ct Diamond AIGL",
        "category":  null,
        "condition":  null,
        "currentBid":  700,
        "askingBid":  750,
        "bidCount":  15,
        "lot":  498665,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum Oscar Friedman Ring, 2.49ct GIA Blue Cushion Sapphire, 0.64ct VS1-F Diamonds, PT900",
        "category":  null,
        "condition":  null,
        "currentBid":  210,
        "askingBid":  215,
        "bidCount":  31,
        "lot":  498666,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Oscar Friedman Platinum Ring, 3.00ct No Heat Blue Sapphire, 0.45ct F-G VS Diamond, GIA Certified",
        "category":  null,
        "condition":  null,
        "currentBid":  235,
        "askingBid":  240,
        "bidCount":  34,
        "lot":  498667,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "14K White Gold Concentric Halo Diamond Ring, 0.75 ct G/SI2 Center, 1.03 ctw, AIGL Appraised",
        "category":  null,
        "condition":  null,
        "currentBid":  310,
        "askingBid":  320,
        "bidCount":  23,
        "lot":  498668,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "Platinum Sapphire \u0026 Diamond Ring 1.01ct Blue Sapphire, 0.91ct Diamonds, 7.5g, AIGL Cert",
        "category":  null,
        "condition":  null,
        "currentBid":  235,
        "askingBid":  240,
        "bidCount":  23,
        "lot":  498669,
        "auctionId":  896,
        "endsAt":  1787184515
    },
    {
        "title":  "2022 FORD E-TRANSIT - 40K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  4100,
        "askingBid":  4200,
        "bidCount":  17,
        "lot":  499532,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2020 FORD TRANSIT 250 - 70K MILES!",
        "category":  null,
        "condition":  null,
        "currentBid":  6200,
        "askingBid":  6300,
        "bidCount":  72,
        "lot":  499533,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2019 FORD TRANSIT - AWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1150,
        "askingBid":  1200,
        "bidCount":  15,
        "lot":  499534,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2019 CHEVROLET EXPRESS CARGO VAN - RWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  2050,
        "askingBid":  2100,
        "bidCount":  16,
        "lot":  499535,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2016 FREIGHTLINER SPRINTER - DIESEL!",
        "category":  null,
        "condition":  null,
        "currentBid":  3400,
        "askingBid":  3500,
        "bidCount":  15,
        "lot":  499536,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2016 FORD TRANSIT",
        "category":  null,
        "condition":  null,
        "currentBid":  1550,
        "askingBid":  1600,
        "bidCount":  17,
        "lot":  499537,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2017 RAM PROMASTER - FWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  1150,
        "askingBid":  1200,
        "bidCount":  7,
        "lot":  499539,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "LOCATED IN MERIDIAN - 2009 CHEVROLET SILVERADO 2500 - DIESEL - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  4600,
        "askingBid":  4700,
        "bidCount":  31,
        "lot":  499541,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2008 FORD F-250 SUPER DUTY - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  2100,
        "askingBid":  2150,
        "bidCount":  9,
        "lot":  499542,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2000 DODGE RAM 2500 - DIESEL!",
        "category":  null,
        "condition":  null,
        "currentBid":  3200,
        "askingBid":  3300,
        "bidCount":  45,
        "lot":  499543,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2005 FORD F-250 - 4X4!",
        "category":  null,
        "condition":  null,
        "currentBid":  1550,
        "askingBid":  1600,
        "bidCount":  15,
        "lot":  499544,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2008 DODGE SPRINTER 3500 - DIESEL!",
        "category":  null,
        "condition":  null,
        "currentBid":  800,
        "askingBid":  850,
        "bidCount":  7,
        "lot":  499545,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2005 FORD E-350 - RWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  650,
        "askingBid":  700,
        "bidCount":  4,
        "lot":  501446,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "2003 FORD F-550 - RWD!",
        "category":  null,
        "condition":  null,
        "currentBid":  500,
        "askingBid":  500,
        "bidCount":  0,
        "lot":  501935,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "72\" Oak Double Sink Milano Collection Bathroom Vanity w/ Quartz Top \u0026 Sinks ML-72-OKV",
        "category":  null,
        "condition":  null,
        "currentBid":  120,
        "askingBid":  125,
        "bidCount":  16,
        "lot":  499546,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1942-S Washington Quarter MS68 GEM, Blazing White, 90% Silver, San Francisco Mint",
        "category":  null,
        "condition":  null,
        "currentBid":  16,
        "askingBid":  17,
        "bidCount":  8,
        "lot":  499547,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Eight Sleep Pod Smart Bed Climate System with Hub and Blanket, Advanced Sleep Tracking \u0026 Cooling",
        "category":  null,
        "condition":  null,
        "currentBid":  115,
        "askingBid":  120,
        "bidCount":  13,
        "lot":  499548,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  21,
        "askingBid":  22,
        "bidCount":  16,
        "lot":  499549,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1934 \u0026 1937 Mercury Dimes, Philadelphia Mint, 90% Silver, Winged Liberty Head, Circulated Coins",
        "category":  null,
        "condition":  null,
        "currentBid":  11,
        "askingBid":  12,
        "bidCount":  3,
        "lot":  499550,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Tineco iFloor 5 Breeze Cordless Floor Washer, 25.2V, Self-Cleaning, Dual Tank, White \u0026 Blue",
        "category":  null,
        "condition":  null,
        "currentBid":  43,
        "askingBid":  45,
        "bidCount":  15,
        "lot":  499551,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Stainless Steel Work Table with Adjustable Undershelf, 34.6\" Height",
        "category":  null,
        "condition":  null,
        "currentBid":  37,
        "askingBid":  39,
        "bidCount":  21,
        "lot":  499552,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1942 \u0026 1943 Mercury Liberty Dimes, 90% Silver, Circulated, Philadelphia Mint Likely",
        "category":  null,
        "condition":  null,
        "currentBid":  11,
        "askingBid":  12,
        "bidCount":  2,
        "lot":  499553,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Modern Blue Fabric Accent Chair with Solid Rubber Wood Legs, 26.8”W x 29.1”D x 35.4”H, 300 lb Capacity",
        "category":  null,
        "condition":  null,
        "currentBid":  10,
        "askingBid":  11,
        "bidCount":  7,
        "lot":  499554,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "ZCMHAXJ 55\" Toddler Trampoline with Enclosure, Giraffe Print, Gymnastics Bar, Accessories",
        "category":  null,
        "condition":  null,
        "currentBid":  27,
        "askingBid":  29,
        "bidCount":  24,
        "lot":  499555,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1944 \u0026 1945 U.S. Mercury Dimes, 90% Silver, Philadelphia Mint",
        "category":  null,
        "condition":  null,
        "currentBid":  11,
        "askingBid":  12,
        "bidCount":  2,
        "lot":  499556,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Eight Sleep Pod Smart Bed Climate System with Hub and Blanket, Advanced Sleep Tracking \u0026 Cooling",
        "category":  null,
        "condition":  null,
        "currentBid":  130,
        "askingBid":  135,
        "bidCount":  25,
        "lot":  499557,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  25,
        "askingBid":  27,
        "bidCount":  11,
        "lot":  499558,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1941 \u0026 1942 Mercury Dimes, 90% Silver, Circulated Condition",
        "category":  null,
        "condition":  null,
        "currentBid":  10,
        "askingBid":  11,
        "bidCount":  3,
        "lot":  499559,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Tineco iFloor 5 Breeze Cordless Floor Washer, 25.2V, Self-Cleaning, Dual Tank, White \u0026 Blue",
        "category":  null,
        "condition":  null,
        "currentBid":  43,
        "askingBid":  45,
        "bidCount":  23,
        "lot":  499560,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "28\" Cocktail Folding Table \u0026 2-Pack Glass Beverage Dispenser Set (2.5 Gal, Wood Stand, Spigot)",
        "category":  null,
        "condition":  null,
        "currentBid":  11,
        "askingBid":  12,
        "bidCount":  6,
        "lot":  499561,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "1944 \u0026 1945 Mercury Silver Dimes - Winged Liberty Head, 90% Silver, Adolph Weinman Design",
        "category":  null,
        "condition":  null,
        "currentBid":  10,
        "askingBid":  11,
        "bidCount":  3,
        "lot":  499562,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Queen Size 6\" Thick Green Quilted Futon Mattress with Washable Cover and Storage Bag",
        "category":  null,
        "condition":  null,
        "currentBid":  29,
        "askingBid":  31,
        "bidCount":  23,
        "lot":  499563,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Sage Velvet Upholstered Ottoman XHOT001-SAGE, Gold Metal Base, 18\"x15\", Drakaconcept",
        "category":  null,
        "condition":  null,
        "currentBid":  6,
        "askingBid":  7,
        "bidCount":  2,
        "lot":  499564,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Dream On Me Synergy 5-in-1 Convertible Full Size Baby Crib, GREENGUARD Gold | BSA Verified, ASTM \u0026 CPSC Tested, 3-Position Mattress Support, Converts to Toddler, Day and Full Size Bed, 50 Lb, Walnut",
        "category":  null,
        "condition":  null,
        "currentBid":  9,
        "askingBid":  10,
        "bidCount":  5,
        "lot":  499565,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  33,
        "askingBid":  35,
        "bidCount":  7,
        "lot":  499566,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Smartliner All-Weather TPE Floor Liners Full Set Black for Front, Rear, Cargo, Patent D782,302",
        "category":  null,
        "condition":  null,
        "currentBid":  20,
        "askingBid":  21,
        "bidCount":  9,
        "lot":  499567,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Castrol TranSynd 668 TES 668 Full Synthetic ATF, 3 x 1-Gallon Bottles, Allison Approved",
        "category":  null,
        "condition":  null,
        "currentBid":  16,
        "askingBid":  17,
        "bidCount":  13,
        "lot":  499568,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Eight Sleep Pod Hub – Smart Sleep System Temperature Regulator with Original Packaging retailing around $2500",
        "category":  null,
        "condition":  null,
        "currentBid":  27,
        "askingBid":  29,
        "bidCount":  8,
        "lot":  499569,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "PHI VILLA THD-1516123 Red Metal Garden Bench with Bird Design, 2-Person Capacity",
        "category":  null,
        "condition":  null,
        "currentBid":  16,
        "askingBid":  17,
        "bidCount":  12,
        "lot":  499570,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "WIPPRO 8KW All-in-One Diesel Air Heater with LCD Display and Remote Control",
        "category":  null,
        "condition":  null,
        "currentBid":  85,
        "askingBid":  90,
        "bidCount":  34,
        "lot":  499571,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "WLIVE Minimalist Wide 8-Drawer Fabric Dresser, Rustic Brown, 39.4\" W x 11.8\" D x 30.4\" H",
        "category":  null,
        "condition":  null,
        "currentBid":  15,
        "askingBid":  16,
        "bidCount":  11,
        "lot":  499572,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  21,
        "askingBid":  22,
        "bidCount":  7,
        "lot":  499573,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Elegant 10x14 Vintage Washable Area Rug, Non-Slip Backing, Stain Resistant, Gray/Blue Pattern",
        "category":  null,
        "condition":  null,
        "currentBid":  25,
        "askingBid":  27,
        "bidCount":  14,
        "lot":  499574,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  21,
        "askingBid":  22,
        "bidCount":  9,
        "lot":  499575,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "HUGHEAVEN Max Giant Bean Bag Chair, Beige, 73.2\"x38.6\"x30.7\", High-Resilience Foam",
        "category":  null,
        "condition":  null,
        "currentBid":  65,
        "askingBid":  70,
        "bidCount":  19,
        "lot":  499576,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Our Place 5-Piece Nonstick Ceramic Bakeware Set – Cast Aluminum, Oven Safe to 450°F, Space-Saving Design",
        "category":  null,
        "condition":  null,
        "currentBid":  20,
        "askingBid":  21,
        "bidCount":  9,
        "lot":  499577,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "HAILUNBAO Kitchen Island Rectangular Crystal Raindrop Chandelier, Green Wave-Shaped Stone Light for Kitchen Romantic Artistic Dining Room Lamps Luxurious Elegant Chrome Light Stairway Chandeliers",
        "category":  null,
        "condition":  null,
        "currentBid":  6,
        "askingBid":  7,
        "bidCount":  2,
        "lot":  499578,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Modern Glass Top Coffee Table, Noguchi-style, Triangular Shape, 50\" x 37.5\" x 16\", Light Oak Finish",
        "category":  null,
        "condition":  null,
        "currentBid":  7,
        "askingBid":  8,
        "bidCount":  3,
        "lot":  499579,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Caesar ASWFP-38 1500W 40\" Black Wall-Mounted Electric Fireplace, Remote, Adjustable Flame, New",
        "category":  null,
        "condition":  null,
        "currentBid":  9,
        "askingBid":  10,
        "bidCount":  5,
        "lot":  499580,
        "auctionId":  897,
        "endsAt":  1787270911
    },
    {
        "title":  "Dyson V8 Cyclone Cordless Stick Vacuum Cleaner, 150 AW Suction, 60-Minute Run Time, Black/Khaki",
        "category":  null,
        "condition":  null,
        "currentBid":  130,
        "askingBid":  135,
        "bidCount":  36,
        "lot":  499581,
        "auctionId":  897,
        "endsAt":  1787270911
    }
];