services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-pricing-agent
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_ENCRYPTION_KEY=qut9yusbJZoRSH0lnanncO4qGuCtAmGSOwRQKVQIibfoiNxz
      - N8N_USER_MANAGEMENT_JWT_SECRET=AzHvlsjPz8ehR3ytAFEIMh7mCfwhjrZcZ0XK6chE500bQuAn
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/.n8n-files;/data
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=America/New_York
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n_data:/home/node/.n8n
      - "C:/Users/wsmit/OneDrive/Documents/Default Project/pricing-intelligence-agent/data:/data"
volumes:
  n8n_data:
